import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/global/Navigation";
import { ClerkProvider } from "@clerk/nextjs";
import TanstackProvider from "@/providers/TanstackProvider";
import { ConfigProvider } from "@/providers/ConfigProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      dynamic
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!}
    >
      <ConfigProvider
        variables={{ BASE_API_URL: process.env.NEXT_PUBLIC_BASE_API_URL! }}
      >
        <TanstackProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navigation />
              {children}
            </body>
          </html>
        </TanstackProvider>
      </ConfigProvider>
    </ClerkProvider>
  );
}
