import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/global/Navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { ConfigProvider } from "@/providers/ConfigProvider";
import { Providers } from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      dynamic
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!}
    >
      <ConfigProvider
        variables={{ BASE_API_URL: process.env.NEXT_PUBLIC_BASE_API_URL! }}
      >
        <Providers>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navigation />
              {children}
              {/* <footer className="flex items-center justify-center w-full h-24 bg-primary-800">
                <p className="text-sm text-center text-background-500">
                  Designed and developed by <a> Samuel Baran </a>
                </p>
              </footer> */}
            </body>
          </html>
        </Providers>
      </ConfigProvider>
    </ClerkProvider>
  );
}
