name: Build and Push to GitHub Container Registry

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Appropriate Image Tags
        id: create_tags
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG=prod-${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_ENV=production" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_ENV=development" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/baranuel/casefiles:${{ steps.create_tags.outputs.TAG }}
            ghcr.io/baranuel/casefiles:latest
      
      - name: Notify infra to deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: Baranuel/casefiles-infra
          event-type: ${{ steps.create_tags.outputs.DEPLOY_ENV }}
          client-payload: '{
              "service": "frontend",
              "tag": "${{ steps.create_tags.outputs.TAG }}"
            }'

  # copy:
  #   name: Copy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
        
  #     - name: rsync deployments
  #       uses: burnett01/rsync-deployments@7.0.2
  #       with:
  #         switches: -avz --delete --exclude node_modules
  #         path: ./
  #         remote_path: /apps/casefiles
  #         remote_host: ${{ secrets.SSH_HOST }}
  #         remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         remote_user: root

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-and-push
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: create env file
  #       run: |
  #         echo -e "\nGIT_COMMIT_HASH=${{ github.sha }}" >> docker/dev/.env
  #         cat docker/dev/.env
  #         sleep 15

   